version: '2'
services:
  NCHC_master:
    container_name: NCHC_master
    image: bigobject/bigobject
    restart: unless-stopped
    logging:
      driver: syslog
      options: 
        syslog-facility: local0
        tag: "{{.Name}}"
    volumes:
        - ./bo/master:/srv/bo/ds
        - ./file:/srv/bo/file
        - ./lua:/srv/bo/lua
        - ./config:/srv/bo/config
    ports:
      - "3306:3306"
      - "9091:9091"
    environment: 
      TZ: Asia/Taipei
      # BO_ENDPOINT: master
      BO_ALIAS: NCHC_master
    networks: 
      - NCHC



  NCHC_client:
    container_name: NCHC_client
    image: bigobject/bigobject
    restart: unless-stopped
    logging:
      driver: syslog
      options: 
        syslog-facility: local0
        tag: "{{.Name}}"
    volumes:
        - ./bo/client01:/srv/bo/ds
        - ./file:/srv/bo/file
        - ./lua:/srv/bo/lua
        - ./config:/srv/bo/config
    ports:
      - "13301:3306"
      - "19091:9091"
    environment: 
      TZ: Asia/Taipei
      BO_MASTER: NCHC_master
      BO_ENDPOINT: NCHC_client
      BO_ALIAS: NCHC_client
    networks: 
      - NCHC

networks: 
  NCHC:
